In [45]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Flatten, Dense
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [46]:
dataset = pd.read_csv('Churn_Modelling.csv')

In [47]:
print(# dataframe.size 
 "size of dataframe",dataset.size
)
print(# dataframe.shape 
 "shape of dataframe",dataset.shape
)
dataset.head()

size of dataframe 140000
shape of dataframe (10000, 14)


RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [48]:
X = dataset.drop(labels=['CustomerId','Surname','RowNumber','Exited'],axis = 1) # here axis=0 represents rows and axis=1 represents columns
Y = dataset['Exited']

In [49]:
X.head(20)

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0           619    France  Female   42       2       0.00              1   
1           608     Spain  Female   41       1   83807.86              1   
2           502    France  Female   42       8  159660.80              3   
3           699    France  Female   39       1       0.00              2   
4           850     Spain  Female   43       2  125510.82              1   
5           645     Spain    Male   44       8  113755.78              2   
6           822    France    Male   50       7       0.00              2   
7           376   Germany  Female   29       4  115046.74              4   
8           501    France    Male   44       4  142051.07              2   
9           684    France    Male   27       2  134603.88              1   
10          528    France    Male   31       6  102016.72              2   
11          497     Spain    Male   24       3       0.00              2   
12          476    France  Female   34      10       0.00              2   
13          549    France  Female   25       5       0.00              2   
14          635     Spain  Female   35       7       0.00              2   
15          616   Germany    Male   45       3  143129.41              2   
16          653   Germany    Male   58       1  132602.88              1   
17          549     Spain  Female   24       9       0.00              2   
18          587     Spain    Male   45       6       0.00              1   
19          726    France  Female   24       6       0.00              2   

    HasCrCard  IsActiveMember  EstimatedSalary  
0           1               1        101348.88  
1           0               1        112542.58  
2           1               0        113931.57  
3           0               0         93826.63  
4           1               1         79084.10  
5           1               0        149756.71  
6           1               1         10062.80  
7           1               0        119346.88  
8           0               1         74940.50  
9           1               1         71725.73  
10          0               0         80181.12  
11          1               0         76390.01  
12          1               0         26260.98  
13          0               0        190857.79  
14          1               1         65951.65  
15          0               1         64327.26  
16          1               0          5097.67  
17          1               1         14406.41  
18          0               0        158684.81  
19          1               1         54724.03

In [50]:
Y.head()

0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

In [51]:
from sklearn.preprocessing import LabelEncoder

In [52]:
label1 = LabelEncoder()
X['Geography'] = label1.fit_transform(X['Geography'])

In [53]:
X.head(20)

CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0           619          0  Female   42       2       0.00              1   
1           608          2  Female   41       1   83807.86              1   
2           502          0  Female   42       8  159660.80              3   
3           699          0  Female   39       1       0.00              2   
4           850          2  Female   43       2  125510.82              1   
5           645          2    Male   44       8  113755.78              2   
6           822          0    Male   50       7       0.00              2   
7           376          1  Female   29       4  115046.74              4   
8           501          0    Male   44       4  142051.07              2   
9           684          0    Male   27       2  134603.88              1   
10          528          0    Male   31       6  102016.72              2   
11          497          2    Male   24       3       0.00              2   
12          476          0  Female   34      10       0.00              2   
13          549          0  Female   25       5       0.00              2   
14          635          2  Female   35       7       0.00              2   
15          616          1    Male   45       3  143129.41              2   
16          653          1    Male   58       1  132602.88              1   
17          549          2  Female   24       9       0.00              2   
18          587          2    Male   45       6       0.00              1   
19          726          0  Female   24       6       0.00              2   

    HasCrCard  IsActiveMember  EstimatedSalary  
0           1               1        101348.88  
1           0               1        112542.58  
2           1               0        113931.57  
3           0               0         93826.63  
4           1               1         79084.10  
5           1               0        149756.71  
6           1               1         10062.80  
7           1               0        119346.88  
8           0               1         74940.50  
9           1               1         71725.73  
10          0               0         80181.12  
11          1               0         76390.01  
12          1               0         26260.98  
13          0               0        190857.79  
14          1               1         65951.65  
15          0               1         64327.26  
16          1               0          5097.67  
17          1               1         14406.41  
18          0               0        158684.81  
19          1               1         54724.03

In [54]:
label = LabelEncoder()
X['Gender'] = label.fit_transform(X['Gender'])

In [55]:
X.tail()

CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
9995          771          0       1   39       5       0.00              2   
9996          516          0       1   35      10   57369.61              1   
9997          709          0       0   36       7       0.00              1   
9998          772          1       1   42       3   75075.31              2   
9999          792          0       0   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  
9995          1               0         96270.64  
9996          1               1        101699.77  
9997          0               1         42085.58  
9998          1               0         92888.52  
9999          1               0         38190.78

In [56]:
X = pd.get_dummies(X, drop_first=True,columns=['Geography']) # one hot encoding using pandas we can also do this using sklearn

In [57]:
X.head(20)

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0           619       0   42       2       0.00              1          1   
1           608       0   41       1   83807.86              1          0   
2           502       0   42       8  159660.80              3          1   
3           699       0   39       1       0.00              2          0   
4           850       0   43       2  125510.82              1          1   
5           645       1   44       8  113755.78              2          1   
6           822       1   50       7       0.00              2          1   
7           376       0   29       4  115046.74              4          1   
8           501       1   44       4  142051.07              2          0   
9           684       1   27       2  134603.88              1          1   
10          528       1   31       6  102016.72              2          0   
11          497       1   24       3       0.00              2          1   
12          476       0   34      10       0.00              2          1   
13          549       0   25       5       0.00              2          0   
14          635       0   35       7       0.00              2          1   
15          616       1   45       3  143129.41              2          0   
16          653       1   58       1  132602.88              1          1   
17          549       0   24       9       0.00              2          1   
18          587       1   45       6       0.00              1          0   
19          726       0   24       6       0.00              2          1   

    IsActiveMember  EstimatedSalary  Geography_1  Geography_2  
0                1        101348.88            0            0  
1                1        112542.58            0            1  
2                0        113931.57            0            0  
3                0         93826.63            0            0  
4                1         79084.10            0            1  
5                0        149756.71            0            1  
6                1         10062.80            0            0  
7                0        119346.88            1            0  
8                1         74940.50            0            0  
9                1         71725.73            0            0  
10               0         80181.12            0            0  
11               0         76390.01            0            1  
12               0         26260.98            0            0  
13               0        190857.79            0            0  
14               1         65951.65            0            1  
15               1         64327.26            1            0  
16               0          5097.67            1            0  
17               1         14406.41            0            1  
18               0        158684.81            0            1  
19               1         54724.03            0            0

In [58]:
#get all unique values from column
dataset.Geography.unique()

array(['France', 'Spain', 'Germany'], dtype=object)

### Feature Standarization

In [64]:
from sklearn.preprocessing import StandardScaler

In [68]:
X_train,X_test, y_train, y_test = train_test_split(X,Y,test_size=0.2,random_state=0,stratify=Y)

In [69]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [70]:
X_train

array([[-1.24021723, -1.09665089,  0.77986083, ...,  1.64099027,
        -0.57812007, -0.57504086],
       [ 0.75974873,  0.91186722, -0.27382717, ..., -1.55587522,
         1.72974448, -0.57504086],
       [-1.72725557, -1.09665089, -0.9443559 , ...,  1.1038111 ,
        -0.57812007, -0.57504086],
       ...,
       [-0.51484098,  0.91186722,  0.87565065, ..., -1.01507508,
         1.72974448, -0.57504086],
       [ 0.73902369, -1.09665089, -0.36961699, ..., -1.47887193,
        -0.57812007, -0.57504086],
       [ 0.95663657,  0.91186722, -1.32751517, ...,  0.50945854,
        -0.57812007,  1.73900686]])

**Build ANN**



In [77]:
#using shift+ double tab will show us the documentation of any function
model = Sequential()
print("Shape of X : ", X.shape[1]) # just to print the value
model.add(Dense(X.shape[1], activation='relu', input_dim=X.shape[1]))
model.add(Dense(128,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

Shape of X :  11


In [78]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [79]:
model.fit(X_train,y_train.to_numpy(),batch_size=10, epochs=10, verbose=1)

Train on 8000 samples
Epoch 1/10
8000/8000 [==============================] - 2s 231us/sample - loss: 0.4517 - accuracy: 0.8062
Epoch 2/10
8000/8000 [==============================] - 1s 158us/sample - loss: 0.3854 - accuracy: 0.8413
Epoch 3/10
8000/8000 [==============================] - 1s 145us/sample - loss: 0.3629 - accuracy: 0.8519
Epoch 4/10
8000/8000 [==============================] - 1s 153us/sample - loss: 0.3528 - accuracy: 0.8550
Epoch 5/10
8000/8000 [==============================] - 1s 142us/sample - loss: 0.3471 - accuracy: 0.8579
Epoch 6/10
8000/8000 [==============================] - 1s 163us/sample - loss: 0.3427 - accuracy: 0.8589
Epoch 7/10
8000/8000 [==============================] - 1s 154us/sample - loss: 0.3385 - accuracy: 0.8595
Epoch 8/10
8000/8000 [==============================] - 1s 127us/sample - loss: 0.3351 - accuracy: 0.8618
Epoch 9/10
8000/8000 [==============================] - 1s 162us/sample - loss: 0.3337 - accuracy: 0.8615
Epoch 10/10
8000/8000 [=

In [80]:
y_pred = model.predict_classes(X_test)

In [81]:
y_pred

array([[0],
       [0],
       [0],
       ...,
       [0],
       [1],
       [0]], dtype=int32)

In [82]:
y_test

1344    1
8167    0
4747    0
5004    1
3124    1
       ..
9107    0
8249    0
8337    0
6279    1
412     0
Name: Exited, Length: 2000, dtype: int64

In [83]:
model.evaluate(X_test,y_test.to_numpy())

2000/2000 [==============================] - 0s 77us/sample - loss: 0.3477 - accuracy: 0.8550


[0.34767388582229614, 0.855]

In [84]:
from sklearn.metrics import confusion_matrix, accuracy_score
confusion_matrix(y_test,y_pred)

array([[1541,   52],
       [ 238,  169]])

In [86]:
accuracy_score(y_test,y_pred)

0.855